#!/bin/bash

i=$(cat /proc/$PPID/cmdline)
if [[ $UID != 0 ]]; then
    echo "Please type sudo $0 $*to use this."
    exit 1
fi

BIN=/usr/local/bin
LIB=/usr/local/lib

if [ ! -d "$LIB/automate" ]; then
    cp ./. $LIB/automate/ -R;
    chmod +x $LIB/automate/automate.sh;
    ln -s $LIB/automate/automate.sh $BIN/automate;
    rm $LIB/automate/install;
    echo "automate installed."
else
     echo "automate already installed.  Skipping."
fi
