#!/bin/bash

#export AUTOMATE_SCRIPTS=/usr/local/lib/automate/scripts;
#export AUTOMATE_SYS=/usr/local/lib/automate/sys;

ZIP_FILE="/tmp/automate-`date +%s`.zip";
wget -O $ZIP_FILE https://github.com/shimarulin/automate/archive/master.zip
unzip -d /tmp $ZIP_FILE;

rm $ZIP_FILE;
rm -rf /tmp/automate-master
